const G=32.174, MPH_TO_FPS=1.46667, BOARD_FRONT_HEIGHT=3.5/12, BOARD_BACK_HEIGHT=1.0, HOLE_DEPTH=3.25, HOLE_Y=BOARD_FRONT_HEIGHT+(BOARD_BACK_HEIGHT-BOARD_FRONT_HEIGHT)*(HOLE_DEPTH/4.0);
const $=id=>document.getElementById(id);
const controls={throwSide:$('throwSide'),boxPosition:$('boxPosition'),handReach:$('handReach'),releaseHeight:$('releaseHeight'),targetDepth:$('targetDepth'),targetZ:$('targetZ'),flightTime:$('flightTime'),dragCalibration:$('dragCalibration'),headWind:$('headWind'),crossWind:$('crossWind'),temperature:$('temperature'),humidity:$('humidity'),elevation:$('elevation'),bagWeight:$('bagWeight'),showIdeal:$('showIdeal')};
const valueEls={boxPosition:$('boxPositionValue'),handReach:$('handReachValue'),releaseHeight:$('releaseHeightValue'),targetDepth:$('targetDepthValue'),targetZ:$('targetZValue'),flightTime:$('flightTimeValue'),dragCalibration:$('dragCalibrationValue'),headWind:$('headWindValue'),crossWind:$('crossWindValue')};
const metrics={x:$('metricX'),vx0:$('metricVx0'),vx1:$('metricVx1'),peak:$('metricPeak'),launch:$('metricLaunch'),azimuth:$('metricAzimuth')};
let current=null, animationFrame=null, animationStarted=null, playing=false;
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
function airDensity(tempF,humidityPct,elevationFt){const tempC=(tempF-32)*5/9,tempK=tempC+273.15,h=elevationFt*.3048,pressure=101325*Math.pow(Math.max(.1,1-2.25577e-5*h),5.25588),sat=610.94*Math.exp((17.625*tempC)/(tempC+243.04)),vapor=clamp(humidityPct,0,100)/100*sat,dry=Math.max(0,pressure-vapor);return dry/(287.058*tempK)+vapor/(461.495*tempK)}
function solveInitialHorizontal(disp,time,k,wind){if(Math.abs(k)<1e-8)return disp/time;return wind+((disp-wind*time)*k)/(1-Math.exp(-k*time))}
function horizontalPosition(start,v0,wind,time,k){if(Math.abs(k)<1e-8)return start+v0*time;return start+wind*time+((v0-wind)/k)*(1-Math.exp(-k*time))}
function horizontalVelocity(v0,wind,time,k){if(Math.abs(k)<1e-8)return v0;return wind+(v0-wind)*Math.exp(-k*time)}
function boardHeight(depth){return BOARD_FRONT_HEIGHT+(BOARD_BACK_HEIGHT-BOARD_FRONT_HEIGHT)*(depth/4.0)}
function calculate(){
  const side=+controls.throwSide.value, boxPosition=+controls.boxPosition.value, reach=+controls.handReach.value, y0=+controls.releaseHeight.value, depth=+controls.targetDepth.value, zTarget=+controls.targetZ.value, T=+controls.flightTime.value, dragCalibration=+controls.dragCalibration.value, headWindMph=+controls.headWind.value, crossWindMph=+controls.crossWind.value, temp=+controls.temperature.value, humidity=+controls.humidity.value, elevation=+controls.elevation.value, weightOz=+controls.bagWeight.value;
  const density=airDensity(temp,humidity,elevation), densityRatio=density/1.225, massFactor=16/Math.max(1,weightOz), k=dragCalibration*densityRatio*massFactor;
  const releaseZ=side*(1+boxPosition), releaseX=reach, impactX=27+depth, impactY=boardHeight(depth), xDisplacement=impactX-releaseX, zDisplacement=zTarget-releaseZ, windX=headWindMph*MPH_TO_FPS, windZ=crossWindMph*MPH_TO_FPS;
  const vx0=solveInitialHorizontal(xDisplacement,T,k,windX), vz0=solveInitialHorizontal(zDisplacement,T,k,windZ), vy0=(impactY-y0+.5*G*T*T)/T, vxImpact=horizontalVelocity(vx0,windX,T,k), vzImpact=horizontalVelocity(vz0,windZ,T,k), vyImpact=vy0-G*T;
  const horizontal0=Math.hypot(vx0,vz0), horizontalImpact=Math.hypot(vxImpact,vzImpact), launchAngle=Math.atan2(vy0,horizontal0)*180/Math.PI, azimuth=Math.atan2(vz0,vx0)*180/Math.PI, impactAngle=Math.atan2(Math.max(0,-vyImpact),horizontalImpact)*180/Math.PI, apexTime=clamp(vy0/G,0,T), apex=sampleAt(apexTime,{releaseX,releaseZ,y0,vx0,vy0,vz0,windX,windZ,k});
  return {side,boxPosition,reach,y0,depth,zTarget,T,dragCalibration,density,densityRatio,k,releaseZ,releaseX,impactX,impactY,xDisplacement,zDisplacement,windX,windZ,headWindMph,crossWindMph,vx0,vz0,vy0,vxImpact,vzImpact,vyImpact,horizontal0,horizontalImpact,launchAngle,azimuth,impactAngle,apex}
}
function sampleAt(t,s){return{t,x:horizontalPosition(s.releaseX,s.vx0,s.windX,t,s.k),y:s.y0+s.vy0*t-.5*G*t*t,z:horizontalPosition(s.releaseZ,s.vz0,s.windZ,t,s.k),vx:horizontalVelocity(s.vx0,s.windX,t,s.k),vy:s.vy0-G*t,vz:horizontalVelocity(s.vz0,s.windZ,t,s.k)}}
function idealSampleAt(t,s){return{t,x:s.releaseX+(s.impactX-s.releaseX)*(t/s.T),y:s.y0+s.vy0*t-.5*G*t*t,z:s.releaseZ+(s.zTarget-s.releaseZ)*(t/s.T)}}
function samples(s,count=160){const out=[],ideal=[];for(let i=0;i<=count;i++){const t=s.T*i/count;out.push(sampleAt(t,s));ideal.push(idealSampleAt(t,s))}return{out,ideal}}
function pathFrom(points,map){return points.map((p,i)=>{const q=map(p);return`${i?'L':'M'} ${q.x.toFixed(2)} ${q.y.toFixed(2)}`}).join(' ')}
function svgEl(tag,attrs={},text=''){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(text)el.textContent=text;return el}
function setupStaticSvgs(){
 const topBoards=$('topBoards'), topBoxes=$('topBoxes'), topGrid=$('topGrid');
 topBoards.append(svgEl('rect',{x:120,y:180,width:90,height:70,rx:6,fill:'var(--panel-2)',stroke:'var(--text)','stroke-width':3}),svgEl('circle',{cx:138,cy:215,r:7,fill:'var(--panel)',stroke:'var(--text)','stroke-width':2}),svgEl('rect',{x:790,y:180,width:90,height:70,rx:6,fill:'var(--panel-2)',stroke:'var(--text)','stroke-width':3}),svgEl('circle',{cx:863,cy:215,r:7,fill:'var(--panel)',stroke:'var(--text)','stroke-width':2}));
 [[120,75],[120,250],[790,75],[790,250]].forEach(([x,y])=>topBoxes.appendChild(svgEl('rect',{x,y,width:90,height:105,rx:7,fill:'var(--panel-2)',opacity:.55,stroke:'var(--border)','stroke-width':2})));
 topGrid.append(svgEl('line',{x1:210,y1:55,x2:210,y2:375,stroke:'var(--danger)','stroke-width':3,'stroke-dasharray':'8 6'}),svgEl('line',{x1:790,y1:55,x2:790,y2:375,stroke:'var(--danger)','stroke-width':3,'stroke-dasharray':'8 6'}),svgEl('text',{x:210,y:40,'text-anchor':'middle',class:'small-label'},'throwing foul line'),svgEl('text',{x:790,y:40,'text-anchor':'middle',class:'small-label'},'target front'));
 const sideGrid=$('sideGrid'), sideMapX=x=>65+((x+3)/35)*890, sideMapY=y=>435-(y/12)*400;
 for(let x=-2;x<=32;x+=2){sideGrid.append(svgEl('line',{x1:sideMapX(x),y1:35,x2:sideMapX(x),y2:435,stroke:'var(--grid)','stroke-width':1}),svgEl('text',{x:sideMapX(x),y:457,'text-anchor':'middle',class:'small-label'},String(x)))}
 for(let y=0;y<=12;y+=2){sideGrid.append(svgEl('line',{x1:65,y1:sideMapY(y),x2:955,y2:sideMapY(y),stroke:'var(--grid)','stroke-width':1}),svgEl('text',{x:55,y:sideMapY(y)+4,'text-anchor':'end',class:'small-label'},String(y)))}
 const endGrid=$('endGrid'), endMapZ=z=>340+(z/5)*280, endMapY=y=>375-(y/12)*350;
 for(let z=-5;z<=5;z++){endGrid.append(svgEl('line',{x1:endMapZ(z),y1:25,x2:endMapZ(z),y2:375,stroke:'var(--grid)','stroke-width':1}),svgEl('text',{x:endMapZ(z),y:397,'text-anchor':'middle',class:'small-label'},String(z)))}
 for(let y=0;y<=12;y+=2){endGrid.append(svgEl('line',{x1:60,y1:endMapY(y),x2:640,y2:endMapY(y),stroke:'var(--grid)','stroke-width':1}),svgEl('text',{x:50,y:endMapY(y)+4,'text-anchor':'end',class:'small-label'},String(y)))}
 const endBoard=$('endBoard'); const zLeft=endMapZ(-1), zRight=endMapZ(1), yFront=endMapY(BOARD_FRONT_HEIGHT), yBack=endMapY(1.0);
 endBoard.append(svgEl('rect',{x:zLeft,y:yBack,width:zRight-zLeft,height:yFront-yBack,fill:'var(--court)',stroke:'var(--text)','stroke-width':2,opacity:.75}),svgEl('ellipse',{cx:endMapZ(0),cy:endMapY(HOLE_Y),rx:15,ry:7,fill:'var(--panel)',stroke:'var(--text)','stroke-width':2}),svgEl('text',{x:340,y:yBack-10,'text-anchor':'middle',class:'small-label'},'target board projection'));
}
function updateSideBoard(){const group=$('sideBoard');group.textContent='';const mapX=x=>65+((x+3)/35)*890,mapY=y=>435-(y/12)*400;const x1=mapX(27),x2=mapX(31),y1=mapY(BOARD_FRONT_HEIGHT),y2=mapY(1.0);group.append(svgEl('polygon',{points:`${x1},${y1} ${x2},${y2} ${x2},${y2+12} ${x1},${y1+12}`,fill:'var(--court)',stroke:'var(--text)','stroke-width':2}),svgEl('line',{x1:x1+12,y1:y1+12,x2:x1+12,y2:435,stroke:'var(--text)','stroke-width':3}),svgEl('line',{x1:x2-12,y1:y2+12,x2:x2-12,y2:435,stroke:'var(--text)','stroke-width':3}),svgEl('ellipse',{cx:mapX(27+HOLE_DEPTH),cy:mapY(HOLE_Y),rx:9,ry:4,fill:'var(--panel)',stroke:'var(--text)','stroke-width':2}),svgEl('text',{x:(x1+x2)/2,y:y2-14,'text-anchor':'middle',class:'small-label'},'board'))}
function setGradient(id,p1,p2){const g=$(id);g.setAttribute('x1',p1.x);g.setAttribute('y1',p1.y);g.setAttribute('x2',p2.x);g.setAttribute('y2',p2.y)}
function setCircle(id,p){const el=$(id);el.setAttribute('cx',p.x);el.setAttribute('cy',p.y)}
function setTextPosition(id,x,y){const el=$(id);el.setAttribute('x',x);el.setAttribute('y',y)}
function render(state){
 current=state; const sampled=samples(state);
 valueEls.boxPosition.textContent=`${state.boxPosition.toFixed(2)} ft`; valueEls.handReach.textContent=`${state.reach.toFixed(2)} ft`; valueEls.releaseHeight.textContent=`${state.y0.toFixed(2)} ft`; valueEls.targetDepth.textContent=`${state.depth.toFixed(2)} ft`; valueEls.targetZ.textContent=`${state.zTarget.toFixed(2)} ft`; valueEls.flightTime.textContent=`${state.T.toFixed(2)} s`; valueEls.dragCalibration.textContent=`${state.dragCalibration.toFixed(3)} s⁻¹`; valueEls.headWind.textContent=`${state.headWindMph.toFixed(1)} mph`; valueEls.crossWind.textContent=`${state.crossWindMph.toFixed(1)} mph`;
 metrics.x.textContent=`${state.xDisplacement.toFixed(2)} ft`; metrics.vx0.textContent=`${state.vx0.toFixed(1)} ft/s`; metrics.vx1.textContent=`${state.vxImpact.toFixed(1)} ft/s`; metrics.peak.textContent=`${state.apex.y.toFixed(2)} ft`; metrics.launch.textContent=`${state.launchAngle.toFixed(1)}°`; metrics.azimuth.textContent=`${state.azimuth.toFixed(1)}°`;
 const loss=state.vx0?100*(state.vx0-state.vxImpact)/state.vx0:0; const windBits=[]; if(Math.abs(state.headWindMph)>.1)windBits.push(`${state.headWindMph>0?'tailwind':'headwind'} ${Math.abs(state.headWindMph).toFixed(1)} mph`); if(Math.abs(state.crossWindMph)>.1)windBits.push(`${state.crossWindMph>0?'rightward':'leftward'} crosswind ${Math.abs(state.crossWindMph).toFixed(1)} mph`); const windText=windBits.length?` With ${windBits.join(' and ')}, the horizontal path bends because drag nudges the bag velocity toward the moving air.`:'';
 $('xExplanation').innerHTML=state.k<1e-8?`With drag at zero, <strong>Vx remains ${state.vx0.toFixed(1)} ft/s</strong> throughout the flight. In this idealized limit, wind does not bend the path because there is no aerodynamic coupling.`:`In this simplified drag model, Vx falls from <strong>${state.vx0.toFixed(1)}</strong> to <strong>${state.vxImpact.toFixed(1)} ft/s</strong> (${loss.toFixed(1)}% loss).${windText}`;
 renderTop(state,sampled); renderSide(state,sampled); renderEnd(state,sampled); updateSideBoard(); setAnimationTime(Math.min(+$('timeScrubber').value,1));
}
function renderTop(state,sampled){const mapX=x=>210+(x/31)*670,mapZ=z=>215+z*34;const d=pathFrom(sampled.out,p=>({x:mapX(p.x),y:mapZ(p.z)}));$('topPath').setAttribute('d',d);$('topPathGlow').setAttribute('d',d);$('topCenterReference').setAttribute('d',`M ${mapX(state.releaseX)} ${mapZ(0)} L ${mapX(state.impactX)} ${mapZ(0)}`);const release={x:mapX(state.releaseX),y:mapZ(state.releaseZ)},impact={x:mapX(state.impactX),y:mapZ(state.zTarget)};setGradient('topGrad',release,impact);setCircle('topRelease',release);setCircle('topImpact',impact);setTextPosition('topReleaseText',release.x+12,release.y-10);setTextPosition('topImpactText',impact.x-58,impact.y-10)}
function renderSide(state,sampled){const mapX=x=>65+((x+3)/35)*890,mapY=y=>435-(y/12)*400;const d=pathFrom(sampled.out,p=>({x:mapX(p.x),y:mapY(p.y)}));$('sidePath').setAttribute('d',d);$('sidePathGlow').setAttribute('d',d);$('sideIdealPath').setAttribute('d',pathFrom(sampled.ideal,p=>({x:mapX(p.x),y:mapY(p.y)})));$('sideIdealPath').style.display=controls.showIdeal.checked&&state.k>1e-8?'':'none';const release={x:mapX(state.releaseX),y:mapY(state.y0)},impact={x:mapX(state.impactX),y:mapY(state.impactY)},apex={x:mapX(state.apex.x),y:mapY(state.apex.y)};setGradient('sideGrad',release,impact);setCircle('sideRelease',release);setCircle('sideImpact',impact);setCircle('sideApex',apex);const arrows=$('velocityArrows');arrows.textContent='';const p=sampleAt(state.T*.52,state),px=mapX(p.x),py=mapY(p.y),vxLen=clamp(Math.abs(p.vx)*3.1,35,125),vyLen=clamp(Math.abs(p.vy)*2.4,18,100),vyDirection=p.vy>=0?-1:1,vxDirection=p.vx>=0?1:-1;arrows.append(svgEl('line',{x1:px,y1:py,x2:px+vxDirection*vxLen,y2:py,stroke:'var(--accent-2)','stroke-width':4}),svgEl('polygon',{points:`${px+vxDirection*vxLen},${py} ${px+vxDirection*(vxLen-12)},${py-7} ${px+vxDirection*(vxLen-12)},${py+7}`,fill:'var(--accent-2)'}),svgEl('text',{x:px+vxDirection*vxLen/2,y:py-9,'text-anchor':'middle',class:'small-label'},`Vx ${p.vx.toFixed(1)}`),svgEl('line',{x1:px,y1:py,x2:px,y2:py+vyDirection*vyLen,stroke:'var(--accent-4)','stroke-width':4}),svgEl('polygon',{points:`${px},${py+vyDirection*vyLen} ${px-7},${py+vyDirection*(vyLen-12)} ${px+7},${py+vyDirection*(vyLen-12)}`,fill:'var(--accent-4)'}),svgEl('text',{x:px+12,y:py+vyDirection*vyLen/2,class:'small-label'},`Vy ${p.vy.toFixed(1)}`))}
function renderEnd(state,sampled){const mapZ=z=>340+(z/5)*280,mapY=y=>375-(y/12)*350;const d=pathFrom(sampled.out,p=>({x:mapZ(p.z),y:mapY(p.y)}));$('endPath').setAttribute('d',d);$('endPathGlow').setAttribute('d',d);const release={x:mapZ(state.releaseZ),y:mapY(state.y0)},impact={x:mapZ(state.zTarget),y:mapY(state.impactY)};setGradient('endGrad',release,impact);setCircle('endRelease',release);setCircle('endImpact',impact)}
function setAnimationTime(frac){if(!current)return;const f=clamp(frac,0,1);$('timeScrubber').value=f;const t=current.T*f,p=sampleAt(t,current);$('timeReadout').textContent=`${t.toFixed(2)} s`;const topMapX=x=>210+(x/31)*670,topMapZ=z=>215+z*34;setCircle('topBag',{x:topMapX(p.x),y:topMapZ(p.z)});const sideMapX=x=>65+((x+3)/35)*890,sideMapY=y=>435-(y/12)*400;setCircle('sideBag',{x:sideMapX(p.x),y:sideMapY(p.y)});const endMapZ=z=>340+(z/5)*280,endMapY=y=>375-(y/12)*350;setCircle('endBag',{x:endMapZ(p.z),y:endMapY(p.y)})}
function animate(timestamp){if(!playing||!current)return;if(animationStarted===null)animationStarted=timestamp;const durationMs=current.T*1000,elapsed=timestamp-animationStarted,fraction=elapsed/durationMs;if(fraction>=1){setAnimationTime(1);playing=false;animationStarted=null;$('playButton').textContent='▶ Animate';return}setAnimationTime(fraction);animationFrame=requestAnimationFrame(animate)}
function togglePlay(){if(playing){playing=false;cancelAnimationFrame(animationFrame);$('playButton').textContent='▶ Animate';return}if(+$('timeScrubber').value>=.999)setAnimationTime(0);playing=true;animationStarted=performance.now()-(+$('timeScrubber').value)*current.T*1000;$('playButton').textContent='❚❚ Pause';animationFrame=requestAnimationFrame(animate)}
function reset(){controls.throwSide.value='1';controls.boxPosition.value='1.5';controls.handReach.value='1.5';controls.releaseHeight.value='4.2';controls.targetDepth.value='2.75';controls.targetZ.value='0';controls.flightTime.value='1.25';controls.dragCalibration.value='0.055';controls.headWind.value='0';controls.crossWind.value='0';controls.temperature.value='77';controls.humidity.value='24';controls.elevation.value='1300';controls.bagWeight.value='16';controls.showIdeal.checked=true;setAnimationTime(0);render(calculate())}
function selectView(view){const views=$('views');document.querySelectorAll('.view-button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(p=>p.classList.toggle('selected',view==='all'||p.dataset.panel===view));views.classList.toggle('single',view!=='all')}
setupStaticSvgs();updateSideBoard();Object.values(controls).forEach(c=>{c.addEventListener('input',()=>render(calculate()));c.addEventListener('change',()=>render(calculate()))});document.querySelectorAll('.view-button').forEach(b=>b.addEventListener('click',()=>selectView(b.dataset.view)));$('timeScrubber').addEventListener('input',e=>{if(playing)togglePlay();setAnimationTime(+e.target.value)});$('playButton').addEventListener('click',togglePlay);$('resetButton').addEventListener('click',reset);render(calculate());